# Generated by Django 4.1.3 on 2022-11-15 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок:')),
                ('memo', models.TextField(blank=True, max_length=1000, verbose_name='Описание:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datecomplited', models.DateTimeField(null=True, verbose_name='Срок исполнения:')),
                ('important', models.BooleanField(default=False, verbose_name='ВАЖНОЕ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
